const P=[...document.querySelectorAll('.page')],yes=$('yes'),no=$('no'),zone=$('zone'),tease=$('tease'),next=$('next'),back=$('back'),progress=$('progress'),prep=$('prep'),mini=$('musicMini'),fallback=$('fallback'),fallbackPlay=$('fallbackPlay');let page=1,loved=false,controller=null,ready=false,playing=false,clicked=false,timer=null;function $(id){return document.getElementById(id)}
for(let i=0;i<22;i++){const h=document.createElement('div');h.className='fh';h.textContent=Math.random()>.38?'♥':'♡';h.style.left=Math.random()*100+'%';h.style.fontSize=10+Math.random()*20+'px';h.style.animationDuration=9+Math.random()*11+'s';h.style.animationDelay=-Math.random()*15+'s';$('float').appendChild(h)}for(let i=0;i<P.length;i++){const d=document.createElement('span');d.className='dot';progress.appendChild(d)}
function nav(){[...progress.children].forEach((d,i)=>d.classList.toggle('on',i===page-1));progress.classList.toggle('show',page>1);back.classList.toggle('show',page>1);next.classList.toggle('show',page>1&&page<P.length)}
function moveNo(){const z=zone.getBoundingClientRect(),b=no.getBoundingClientRect(),mx=Math.max(10,z.width-b.width-10),my=Math.max(10,z.height-b.height-10);no.style.right='auto';no.style.left=10+Math.random()*Math.max(1,mx-10)+'px';no.style.top=10+Math.random()*Math.max(1,my-10)+'px';const a=['어라? 😶','진짜…?','다시 생각해봐 👀','그 버튼 맞아?','도망간다 🏃','정답은 반대쪽인데? 😌'];tease.textContent=a[Math.floor(Math.random()*a.length)]}['mouseenter','pointerdown','touchstart'].forEach(e=>no.addEventListener(e,x=>{x.preventDefault();moveNo()},{passive:false}));no.onclick=e=>{e.preventDefault();moveNo()}
function burst(n=34){const b=document.createElement('div');b.className='burst';document.body.appendChild(b);for(let i=0;i<n;i++){const x=document.createElement('i');x.textContent=i%3?'♥':'♡';x.style.setProperty('--x',(Math.random()*350-175)+'px');x.style.setProperty('--y',(Math.random()*330-185)+'px');x.style.setProperty('--r',(Math.random()*280-140)+'deg');b.appendChild(x)}setTimeout(()=>b.remove(),1000)}
function show(n){if(n<1||n>P.length||(page===1&&!loved&&n>1))return;const c=P[page-1];c.classList.add('exit');c.classList.remove('active');setTimeout(()=>c.classList.remove('exit'),540);page=n;P[page-1].classList.add('active');nav()}next.onclick=()=>show(page+1);back.onclick=()=>show(page-1);$('secret').onclick=()=>$('secretText').classList.toggle('show');$('finalYes').onclick=()=>{burst(48);$('finalMsg').classList.add('show')}
function enableYes(){ready=true;yes.disabled=false;yes.textContent='응 ♥';prep.textContent='준비됐어. 눌러봐 ♥'}
window.onSpotifyIframeApiReady=IFrameAPI=>{IFrameAPI.createController($('spotifyHost'),{width:320,height:152,uri:'spotify:track:6x01fGn7wBcgbULOPWnErb'},c=>{controller=c;c.addListener('ready',enableYes);c.addListener('playback_started',()=>{playing=true;mini.classList.remove('paused');fallback.classList.remove('show');clearTimeout(timer)});c.addListener('playback_update',e=>{if(e&&e.data){playing=!e.data.isPaused;mini.classList.toggle('paused',!playing)}})})}
setTimeout(()=>{if(!ready){yes.disabled=false;yes.textContent='응 ♥';prep.textContent='눌러봐 ♥'}},4000)
function start(){mini.classList.add('show');if(controller&&ready){try{controller.restart();controller.play()}catch(e){}}clearTimeout(timer);timer=setTimeout(()=>{if(!playing)fallback.classList.add('show')},1900)}
yes.onclick=()=>{if(clicked)return;clicked=true;loved=true;yes.textContent='나도 사랑해 ♥';tease.textContent='그럴 줄 알았어 :)';prep.textContent='우리 노래도 같이 시작할게 ♥';burst();start();setTimeout(()=>show(2),720)}
mini.onclick=()=>{if(!controller)return;if(playing){controller.pause();playing=false;mini.classList.add('paused')}else{try{controller.resume()}catch(e){controller.play()};mini.classList.remove('paused')}};fallbackPlay.onclick=()=>{fallback.classList.remove('show');if(controller){try{controller.restart();controller.play()}catch(e){}}}
async function txt(u){const r=await fetch(u,{cache:'force-cache'});if(!r.ok)throw Error(u);return(await r.text()).trim()}async function photo(id,parts){try{const d=(await Promise.all(parts.map(txt))).join('');$(id).src='data:image/webp;base64,'+d}catch(e){console.error(e)}}photo('photo1',['love-data-v4/p1a.txt?v=8','love-data-v4/p1b.txt?v=8']);photo('photo2',['love-data-v4/p2.txt?v=8']);photo('photo3',['love-data-v4/p3.txt?v=8']);photo('photo4',['love-data-v4/p4.txt?v=8']);nav();